### PR TITLE
[NO-TASK] maven configuration to use jdk 20

### PR DESCRIPTION
**Pull request by pavelvrublevskij**

### CODE REVIEW

**Comment by ernestaskriskus** [comment]
Thank you for clarifying.

**Comment by AntiQnis** [comment]
Looks good i agree

**Comment by AndDauJA** [comment]
Wat the hell was that?

**Review by pavelvrublevskij — COMMENTED** [review]
All good

**Review by AndDauJA — CHANGES_REQUESTED** [review]
man spalvos netinka :)

**Review by DovydasBerzanskas — COMMENTED** [review]
Sueis

**Pull request merged**
